In [3]:
xl = [1, 2, 3, 4, 5]

In [7]:
"".join(map(lambda x: str(int(x)), xl))

'12345'

In [11]:
int("".join([str(int(x)) for x in xl]))

12345

In [13]:
import numpy as np
x = np.array([0.2, 6.4, 3.0, 1.6])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])
inds = np.digitize(x, bins)
inds

array([1, 4, 3, 2], dtype=int64)

In [14]:
np.linspace(-1, 1, 10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [15]:
c = [1] * 50 + [2] * 50 

In [31]:
from statistics import mean

In [37]:
from sklearn.linear_model import SGDRegressor

In [39]:
model = SGDRegressor()

In [40]:
model.partial_fit([[0, 0]], [0])

SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [41]:
model.predict([[0, 0]])

array([0.])

In [42]:
model.predict([[99, 99]])

array([0.])

In [120]:
from sklearn.kernel_approximation import RBFSampler
X = [[0], [5]]
y = [0]
rbf_feature = RBFSampler(gamma=1, random_state=3, n_components=5)

In [121]:
X

[[0], [5]]

In [122]:
X_features = rbf_feature.fit_transform(X)
X_features

array([[ 0.59967372, -0.58921936,  0.62134499, -0.60933515, -0.37449445],
       [ 0.5814108 ,  0.57569377,  0.40779612, -0.4021222 , -0.32866847]])

In [125]:
rbf_feature.transform([[0],[1],[2],[4]])

array([[ 0.59967372, -0.58921936,  0.62134499, -0.60933515, -0.37449445],
       [-0.60627907, -0.61350494,  0.59951117,  0.61507338, -0.54089112],
       [ 0.39274319, -0.41132594,  0.56652966, -0.46653339, -0.62511287],
       [-0.33283041,  0.31785572,  0.46977255,  0.11499669, -0.51027844]])